DROP TABLE IF EXISTS JAVA_SCRIPT_FRAMEWORK_VERSION;
DROP TABLE IF EXISTS JAVA_SCRIPT_FRAMEWORK;

CREATE TABLE JAVA_SCRIPT_FRAMEWORK
(
    JAVA_SCRIPT_FRAMEWORK_ID BIGINT IDENTITY PRIMARY KEY,
    NAME                     VARCHAR(30) NOT NULL
);

CREATE TABLE JAVA_SCRIPT_FRAMEWORK_VERSION
(
    JAVA_SCRIPT_FRAMEWORK_ID BIGINT      NOT NULL,
    JAVA_SCRIPT_FRAMEWORK_NO BIGINT      NOT NULL,
    VERSION                  VARCHAR(30) NOT NULL,
    DEPRECATION_DATE         DATE        NULL,
    HYPE_LEVEL               VARCHAR(30) NOT NULL,
    PRIMARY KEY (JAVA_SCRIPT_FRAMEWORK_ID, JAVA_SCRIPT_FRAMEWORK_NO)
);