INSERT INTO JAVA_SCRIPT_FRAMEWORK(NAME)
VALUES ('Angular'),
       ('Spring Framework');

INSERT INTO JAVA_SCRIPT_FRAMEWORK_VERSION(JAVA_SCRIPT_FRAMEWORK_ID, JAVA_SCRIPT_FRAMEWORK_NO, VERSION,
                                          DEPRECATION_DATE, HYPE_LEVEL)
VALUES ((SELECT JSF.JAVA_SCRIPT_FRAMEWORK_ID
         FROM JAVA_SCRIPT_FRAMEWORK AS JSF
         WHERE JSF.NAME = 'Angular'
         LIMIT 1), 0, 'JS', '2017-12-12', 'LOW'),
       ((SELECT JSF.JAVA_SCRIPT_FRAMEWORK_ID
         FROM JAVA_SCRIPT_FRAMEWORK AS JSF
         WHERE JSF.NAME = 'Angular'
         LIMIT 1), 1, '10.0.0', '2020-12-24', 'NORMAL'),
       ((SELECT JSF.JAVA_SCRIPT_FRAMEWORK_ID
         FROM JAVA_SCRIPT_FRAMEWORK AS JSF
         WHERE JSF.NAME = 'Angular'
         LIMIT 1), 2, '999.0.0', null, 'HIGH'),
       ((SELECT JSF.JAVA_SCRIPT_FRAMEWORK_ID
         FROM JAVA_SCRIPT_FRAMEWORK AS JSF
         WHERE JSF.NAME = 'Spring Framework'
         LIMIT 1), 0, '4.0.4', '2020-12-12', 'NORMAL');
